### ISSUE TITLE
cc_insert() doesnt compile if compound literal doesnt wrapped up with extra braces.

### ISSUE THREAD

**Issue by apilatosba** [JacksonAllan/CC#11]
Good morning.
Basically if i have a map with custom struct and try to insert to it and use compund literals without extra braces it doesnt compile.
```c
cc_insert(&customValueMap, "Player", (Player){.id = 10, .name = "Player 10"}); // this line doesnt compile
```
if i wrap it up with extra braces it does compile:
```c
cc_insert(&customValueMap, "Player", ((Player){.id = 10, .name = "Player 10"})); // this line compiles
```
I am a noob c guy. I dont know if it is a bug or not but looks like it is not intended to me.
I created a minimal program that demonstrates this. https://github.com/apilatosba/cc-issue-demo
i hope you a great day my friend.

**Comment by JacksonAllan** [comment]
Hi!

This is, sadly, just a [quirk of the C preprocessor](https://stackoverflow.com/questions/5558159/compound-literals-and-function-like-macros-bug-in-gcc-or-the-c-standard) and the way it parses macro arguments. To the preprocessor, curly braces, unlike normal braces, aren’t significant and therefore don’t shield commas. So in your example, the preprocessor actually understands four, not three, macro arguments: `&customValueMap`, `"Player"`, `(Player){.id = 10`, and `.name = "Player 10"}`.

The application-level solution is for the user to enclose any compound-literal argument in braces, exactly as you suggested. I should perhaps add a note about this to CC's documentation, although the issue exists for all function-like macros in C, including those in the standard library.

Inside CC's code, not much can be done. When the parameter in question is the last one, we could circumvent the problem by replacing it with `…` (i.e. `__VA_ARGS__`). But in other cases, we’re stuck. So for `cc_insert` and maps, for example, we could fix the issue for the element parameter but not the key parameter (which might also take a compound literal argument). It's a partial solution, and that’s why I didn’t apply it when designing the macros. In other words, I'd prefer to keep the behavior consistent across all macros and arguments.

**Comment by apilatosba** [comment]
i see. thanks for the explanation. i dont think you need to note this in the docs since the issue is not caused by your implementation but it is a c thing in general.
